### ISSUE TITLE
Texture2DData does not exist.

### ISSUE THREAD

**Issue by lontis** [rsahlin/graphics-by-opengl#1]
com.nucleus.texturing.Texture2DData does not seem to currently exist in your repository :)
so 'import com.nucleus.texturing.Texture2DData' lines currently produce an error.

**Comment by rsahlin** [comment]
Hi Shane and thanks for the comment.
Could you please try again, I have made a lot of changes to the texture setup.
Texture classes should now be serialized from JSON and not use the ..Data scheme.
- Could you please try fetching again?
